# Generated by Django 3.1.2 on 2020-11-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=300)),
                ('vip_seats', models.IntegerField()),
                ('premium_seats', models.IntegerField()),
                ('executive_seats', models.IntegerField()),
                ('normal_seats', models.IntegerField()),
            ],
        ),
    ]
