# Generated by Django 3.1.3 on 2020-12-16 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('useradmin', '0003_dealer_theatre_close'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NowShowingMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=300, null=True)),
                ('cast_name', models.CharField(max_length=300, null=True)),
                ('director_name', models.CharField(max_length=300, null=True)),
                ('release_date', models.DateTimeField()),
                ('show_time', models.DateTimeField()),
                ('runtime_hour', models.IntegerField(blank=True, default=0, null=True)),
                ('runtime_minute', models.IntegerField(blank=True, default=0, null=True)),
                ('language', models.CharField(max_length=300, null=True)),
                ('movie_type', models.CharField(max_length=200, null=True)),
                ('trailer_link', models.URLField(max_length=500)),
                ('photo_banner', models.ImageField(blank=True, null=True, upload_to='')),
                ('photo_main', models.ImageField(blank=True, null=True, upload_to='')),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useradmin.dealer')),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=300, null=True)),
                ('cast_name', models.CharField(max_length=300, null=True)),
                ('director_name', models.CharField(max_length=300, null=True)),
                ('language', models.CharField(max_length=300, null=True)),
                ('movie_type', models.CharField(max_length=200, null=True)),
                ('trailer_link', models.URLField(max_length=500)),
                ('photo_banner', models.ImageField(blank=True, null=True, upload_to='')),
                ('photo_main', models.ImageField(blank=True, null=True, upload_to='')),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useradmin.dealer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeatSelected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupied_seats', models.CharField(max_length=300, null=True)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useradmin.dealer')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theatre.nowshowingmovies')),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=300)),
                ('row', models.IntegerField(blank=True, null=True)),
                ('vip_seats', models.IntegerField()),
                ('vip_price', models.IntegerField(blank=True, null=True)),
                ('premium_seats', models.IntegerField()),
                ('premium_price', models.IntegerField(blank=True, null=True)),
                ('executive_seats', models.IntegerField()),
                ('executive_price', models.IntegerField(blank=True, null=True)),
                ('normal_seats', models.IntegerField()),
                ('normal_price', models.IntegerField(blank=True, null=True)),
                ('select', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='nowshowingmovies',
            name='screen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theatre.screen'),
        ),
        migrations.AddField(
            model_name='nowshowingmovies',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=300, null=True)),
                ('phone_number', models.CharField(max_length=300, null=True)),
                ('firstname', models.CharField(max_length=300, null=True)),
                ('date_booking', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('transaction_id', models.CharField(max_length=200, null=True)),
                ('order_status', models.CharField(default='Success', max_length=200, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_status', models.CharField(max_length=300, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theatre.customer')),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useradmin.dealer')),
                ('seatSelect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theatre.seatselected')),
            ],
        ),
    ]
