# Generated by Django 3.1.3 on 2020-12-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0002_auto_20201216_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowshowingmovies',
            name='show_date',
            field=models.DateTimeField(),
        ),
    ]
