# Generated by Django 3.1.2 on 2020-11-09 17:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0003_nowshowingmovies'),
    ]

    operations = [
        migrations.AddField(
            model_name='nowshowingmovies',
            name='show_time',
            field=models.TimeField(auto_now_add=True, default=datetime.datetime(2020, 11, 9, 17, 51, 11, 521793, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
