# Generated by Django 3.1.3 on 2020-12-16 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0003_auto_20201216_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nowshowingmovies',
            name='show_time',
        ),
    ]
