# Generated by Django 3.1.3 on 2020-12-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0004_remove_nowshowingmovies_show_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='payment_status',
            field=models.CharField(default='cash', max_length=300, null=True),
        ),
    ]
