# Generated by Django 3.1.2 on 2020-11-09 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theatre', '0004_nowshowingmovies_show_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=300, null=True)),
                ('cast_name', models.CharField(max_length=300, null=True)),
                ('director_name', models.CharField(max_length=300, null=True)),
                ('language', models.CharField(max_length=300, null=True)),
                ('movie_type', models.CharField(max_length=200, null=True)),
                ('trailer_link', models.URLField()),
                ('photo_banner', models.ImageField(blank=True, null=True, upload_to='')),
                ('photo_main', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
