# Generated by Django 3.1.3 on 2020-11-26 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0006_auto_20201109_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='nowshowingmovies',
            name='screen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theatre.screen'),
        ),
    ]
