# Generated by Django 3.1.3 on 2020-11-26 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0007_nowshowingmovies_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='select',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nowshowingmovies',
            name='screen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theatre.screen'),
        ),
    ]
