# Generated by Django 3.1.3 on 2020-11-27 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0003_dealer_theatre_close'),
        ('theatre', '0008_auto_20201126_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='nowshowingmovies',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useradmin.dealer'),
        ),
    ]
