# Generated by Django 3.1.3 on 2020-12-01 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0003_dealer_theatre_close'),
        ('theatre', '0011_upcomingmovies_dealer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatSelected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupied_seats', models.CharField(max_length=300, null=True)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useradmin.dealer')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theatre.nowshowingmovies')),
            ],
        ),
    ]
