# Generated by Django 3.1.3 on 2020-12-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0012_seatselected'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='row',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
