# Generated by Django 3.1.3 on 2020-12-02 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('useradmin', '0003_dealer_theatre_close'),
        ('theatre', '0013_screen_row'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=300, null=True)),
                ('phone_number', models.CharField(max_length=300, null=True)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useradmin.dealer')),
                ('movies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theatre.nowshowingmovies')),
                ('seatSelect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theatre.seatselected')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
