# Generated by Django 3.1.3 on 2020-12-06 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0003_dealer_theatre_close'),
        ('theatre', '0016_auto_20201206_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=300, null=True)),
                ('phone_number', models.CharField(max_length=300, null=True)),
                ('firstname', models.CharField(max_length=300, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theatre.customer')),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useradmin.dealer')),
                ('movies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theatre.nowshowingmovies')),
                ('seatSelect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theatre.seatselected')),
            ],
        ),
    ]
