# Generated by Django 3.1.3 on 2020-12-06 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0017_bookingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booked',
            old_name='date_orderd',
            new_name='date_booking',
        ),
        migrations.RemoveField(
            model_name='bookingaddress',
            name='dealer',
        ),
    ]
