# Generated by Django 3.1.3 on 2020-12-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0019_auto_20201206_1010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingAddress',
        ),
    ]
