# Generated by Django 3.1.3 on 2020-12-06 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0003_dealer_theatre_close'),
        ('theatre', '0020_delete_bookingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useradmin.dealer'),
        ),
        migrations.AddField(
            model_name='booked',
            name='email',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='booked',
            name='firstname',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='booked',
            name='phone_number',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
