# Generated by Django 3.1.3 on 2020-11-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='theatre_location',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
