# Generated by Django 3.1.3 on 2020-11-27 04:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0002_dealer_theatre_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='theatre_close',
            field=models.TimeField(auto_now_add=True, default=datetime.datetime(2020, 11, 27, 4, 22, 5, 350538, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
